steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-image:latest']

images:
  - 'gcr.io/$PROJECT_ID/my-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: all-buy-service-account@all-buy-tools.iam.gserviceaccount.com
